# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "quiet-credit-7cb4"
main = "src/index.ts"
compatibility_date = "2025-01-24"

[observability]
enabled = true

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# Uncomment and configure if needed
# [placement]
# mode = "smart"

# Bindings
# Bindings allow your Worker to interact with resources on the Cloudflare Developer Platform, including
# databases, object storage, AI inference, real-time communication, and more.
# https://developers.cloudflare.com/workers/runtime-apis/bindings/

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# Uncomment and configure if needed
# [vars]
# MY_VARIABLE = "production_value"

# Static Assets
# https://developers.cloudflare.com/workers/static-assets/binding/
# Uncomment and configure if needed
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# Uncomment and configure if needed
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# D1 Databases
# Add your database configuration here
[[d1_databases]]
binding = "DB"
database_name = "booking-database1"
database_id = "353237f7-35e1-4555-952e-30f3469b95d7"
migrations_dir = "migrations"

[site]
bucket = "./public" # Directory containing static files

